### ISSUE TITLE
Examples are not working anymore

### ISSUE THREAD

**Issue by deepfriedbrain** [oliverzy/process-engine.js#4]
When I tried to run the project, I got the following error:

c:\dev\process-engine\ui>brunch watch --server
09 May 17:02:32 - info: starting custom server
09 May 17:02:32 - info: custom server started, initializing watcher

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1001:11)
  at Process.ChildProcess._handle.onexit (child_process.js:792:34)

I fixed this by updating the following line in ui/nodemon-wrapper.js:
 
var server = child_process.spawn('nodemon.cmd', ['--watch', '../node_modules/process-engine/src', '--watch','.' ,'server.js'], {cwd: 'server'});

(nodemon changed to nodemon.cmd)

Then I could get the server up, but had the following resources missing (404):

GET / 200 20ms - 2.26kb
GET /diagram-viewer/style.css 404 21ms
GET /css/app.css 404 16ms
GET /js/diagram-viewer.js 404 14ms
GET /js/app.js 404 13ms
GET /css/vendor.css 200 47ms - 196.32kb
GET /js/vendor.js 200 249ms - 2.57mb
GET /fonts/fontawesome-webfont.woff?v=4.0.3 200 5ms - 43.39kb

I'm new to node.js and not sure how to address these issues. Any help will be appreciated. 

Thanks.

**Comment by sandip8600** [comment]
@deepfriedbrain  did you succeed in getting this working?
I am getting `error: Initialization error -  can't use npm integration with non-Common
JS modules format `

**Comment by deepfriedbrain** [comment]
Not really. The project in which I was trying to use this library didn't go through due to other reasons.
