### ISSUE TITLE
Install issue - can't use npm integration with non-CommonJS modules 

### ISSUE THREAD

**Issue by thim81** [oliverzy/process-engine.js#6]
After following the installation steps:

- Go to ui folder
- Run npm install
- Run bower install
- Run npm install -g nodemon

When running

```
brunch watch --server
````

I get the following error:

```
 - error: Initialization error -  can't use npm integration with non-CommonJS modules format (current: 'false'/'function (path, data) {
      if (!endWith(path, 'joint.nojquerynobackbone.js') &&
          !endWith(path, 'joint.layout.DirectedGraph.js') &&
          !startsWith(path, 'app/diagram-viewer')) {
        return "(function() {\n  " + data + "\n}());\n\n";
      } else {
        return "" + data;
      }
    })'. Either set 'config.modules.definition' and 'config.modules.wrapper' to 'commonjs' or disable npm integration ('config.npm.enabled = false')
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
```

Any idea what I'm doing wrong?

**Comment by oliverzy** [comment]
I think you need to use old brunch version.
e.g. `npm install brunch@1.8.5 -g`

**Comment by thim81** [comment]
Hi Oliverzy,

The downgrade of brunch did help but, the ```brunch watch --server````

now complaints about a missing: config

````
usr/local/lib/node_modules/brunch/lib/helpers.js:592
      throw new Error("couldn\'t load config " + fullPath + ". " + error);

Error: couldn't load config /process-engine/config. Error: Cannot find module '/process-engine/config'
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:592:13)
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:590:22)
  at initialize (/usr/local/lib/node_modules/brunch/lib/watch.js:461:18)
  at new BrunchWatcher (/usr/local/lib/node_modules/brunch/lib/watch.js:650:5)
  at module.exports.watch (/usr/local/lib/node_modules/brunch/lib/watch.js:716:10)
  at start (/usr/local/lib/node_modules/brunch/lib/index.js:15:31)
  at Command.listener (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:289:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:572:12)
  at Command.parse (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:438:21)
  at Object.exports.run (/usr/local/lib/node_modules/brunch/lib/cli.js:63:11)
  at Object.<anonymous> (/usr/local/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at startup (node.js:136:18)
  at node.js:966:3
```

**Comment by KrishnaPG** [comment]
Getting this same error - how to get rid of it. The project was created with `brunch new` and `brunch watch -s` is giving that error

**Comment by bretonio** [comment]
Also with me, running `brunch w -s` in a template called `brunch-whey` ...

**Comment by bretonio** [comment]
Downgrading to brunch@1.8.5 did it for me thanks.
